# System part
os:
  - linux

# Java specific
language: java
jdk:
  - openjdk8

# Installation
addons:
  apt:
    packages:
    - swig

scripts:
  ./gradlew b --info

# Gradle specific
cache:
  directories:
  - $HOME/.gradle
