# System part
os:
  - linux
sudo: required

# Java specific
language: java
jdk:
  - openjdk8

# Installation
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install swig

install:
  - git clone --depth=50 --branch=master https://github.com/mmorise/World.git World

scripts:
  ./gradlew b --info

# Gradle specific
cache:
  directories:
  - $HOME/.gradle
