# SCM part
branches:
  only:
    - master

# System part
os:
  - linux

# Java specific
language: java
jdk:
  - openjdk8

# Installation
addons:
  apt:
    packages:
    - swig

scripts:
  ./gradlew b --info

# Gradle specific
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
